### ISSUE TITLE
github3.exceptions.AuthenticationFailed: 401 A JSON web token could not be decoded

### ISSUE THREAD

**Issue by maestro1315** [3rd-party-integrations/github-team-sync#136]
Can anyone offer some insight on this error I'm receiving in the Github docker image using Okta for authentication ? 
github3.exceptions.AuthenticationFailed: 401 A JSON web token could not be decoded

**Comment by cn137** [comment]
Seeing a similar issue when using LDAP for Authentication

**Comment by primetheus** [comment]
@maestro1315 @cn137 I'm not sure what's causing your issue, but if you could upload a redacted portion of the log I might be able to debug it better. I'm going to be working on #83 and #115, which may also solve your issue

**Comment by cn137** [comment]
I started all over and the issues seems to have resolved itself. Muts have been some sort of user error, unable to pin point what it was.

**Comment by primetheus** [comment]
Closing this one out. If you need assistance in the future, please don't hesitate to reach back out!
