### ISSUE TITLE
Support to change Cron interval in githubapp/__init__.py 

### ISSUE THREAD

**Issue by ryadamreddy** [3rd-party-integrations/github-team-sync#139]
Hi Team, we are trying to minimize the cron interval to every 5 minutes. Is there anyway to customize 'CRON_INTERVAL' param?

https://github.com/github/github-team-sync/blob/main/githubapp/__init__.py#L29

**Comment by Chocrates** [comment]
CRON is configurable here https://github.com/github/github-team-sync/blob/main/.env.example.aad#L77

Is this not what you are looking for?

**Comment by primetheus** [comment]
@ryadamreddy can you confirm if the answer above solves your question?

**Comment by primetheus** [comment]
@ryadamreddy I'm closing this as it appears to have been addressed. Please feel free to re-open if you need additional help
