### ISSUE TITLE
Add possibility to Filter AAD Groups

### ISSUE THREAD

**Issue by StevDa86** [3rd-party-integrations/github-team-sync#142]
Please add the possibility that I can filter AAD groups before sync. 
For example, I only want to sync groups to Github that have the prefix "TEST-".

**Comment by IAmHughes** [comment]
I would also like to see this. I can imagine for testing, but also for potentially improved search in looking up teams as the filter could return only a subset of teams through the Graph API perhaps?

**Comment by primetheus** [comment]
@StevDa86 this is implemented in #180... please let me know if this addresses your need
