### ISSUE TITLE
Github-bot-api

### ISSUE THREAD

**Issue by Macasore** [3rd-party-integrations/github-team-sync#145]
please i'm building a github bot with python and i've followed the necessary documentations but now im getting an error which says:
AttributeError: module 'github' has no attribute 'Github'. Did you mean: 'GithubApp'?
and when i change it to GithubApp i get this error:
TypeError: 'module' object is not callable
please help

**Comment by primetheus** [comment]
@Macasore apologies for the late reply... can you detail the steps you took in order to reach that error?

1. Which version of Python are you using?
2. What steps (specifically each command) are you running, and in which order?
3. What is the output of each step?

**Comment by primetheus** [comment]
@Macasore if you still need assistance please feel free to reach back out
