### ISSUE TITLE
[Feature Request] Add Google Workspace source

### ISSUE THREAD

**Issue by dm3ch** [3rd-party-integrations/github-team-sync#151]
I believe it would be useful to be able to sync github teams with Google Workspace groups.

Google provides a REST api that could be used to fetch groups and group members info:
https://developers.google.com/admin-sdk/directory/reference/rest/v1/groups
https://developers.google.com/admin-sdk/directory/reference/rest/v1/members

It seems google also have a python library to work with this API. Here's an official example - https://github.com/googleworkspace/python-samples/blob/main/admin_sdk/directory/quickstart.py

**Comment by primetheus** [comment]
@dm3ch thanks for opening this up! It does sound useful, and I don't think it would be a heavy lift to implement
