### ISSUE TITLE
Unable to run the Dockerfile failing with Pipinstall

### ISSUE THREAD

**Issue by ta6x3y5-bronga** [3rd-party-integrations/github-team-sync#172]
We are trying to build this application and while we running the dockerfile we are getting the issue 

#0 1.239 Installing dependencies from Pipfile.lock (a93130)...
#0 46.75 An error occurred while installing aenum==3.1.12 --hash=sha256:2d544ef7323c088d68abf9a84b9f3f6db0d516fec685e15678b5f84fdb7b8ba0 --hash=sha256:3e531c91860a81f885f7e6e97d219ae9772cb899580084788935dad7d9742ef0 --hash=sha256:8d79c9e3ec997220e355b96b322e672fb56a53e61744138ed838407e3a07b610! Will try again.
#0 46.75 An error occurred while installing aiohttp==3.8.4 ; python_version >= '3.6' --hash=sha256:03543dcf98a6619254b409be2d22b51f21ec66272be4ebda7b04e6412e4b2e14 --hash=sha256:03baa76b730e4e15a45f81dfe29a8d910314143414e528737f8589ec60cf7391 --hash=sha256:0a63f03189a6fa7c900226e3ef5ba4d3bd047e18f445e69adbd65af433add5a2 --hash=sha256:10c8cefcff98fd9168cdd86c4da8b84baaa90bf2da2269c6161984e6737bf23e --hash=sha256:147ae376f14b55f4f3c2b118b95be50a369b89b38a971e80a17c3fd623f280c9 --hash=sha256:176a64b24c0935869d5bbc4c96e82f89f643bcdf08ec947701b9dbb3c956b7dd --hash=sha256:17b79c2963db82086229012cff93ea55196ed31f6493bb1ccd2c62f1724324e4 --hash=sha256:1a45865451439eb320784918617ba54b7a377e3501fb70402ab8

**Comment by primetheus** [comment]
thanks @ta6x3y5-bronga! I'll take a look and see if we can get this resolved quickly

**Comment by primetheus** [comment]
@ta6x3y5-bronga this is fixed in #178
