### ISSUE TITLE
load_custom_map fails if there is no ignore users are present in syncmap.yml

### ISSUE THREAD

**Issue by ta6x3y5-bronga** [3rd-party-integrations/github-team-sync#191]

**Comment by ta6x3y5-bronga** [comment]
Our syncmap.yml file has only value
---
mapping:
  - github: team A
    directory: team A
    org: my-org
But its failing to load load_custom_map becuase of this error

File "/opt/github-team-sync/app.py", line 302, in sync_all_teams
    custom_map, _ = load_custom_map()
ValueError: too many values to unpack (expected 2)

**Comment by Smirl** [comment]
Is this fixed by https://github.com/3rd-party-integrations/github-team-sync/pull/190?

@primetheus could you please review as we are blocked by this as well. Thank you!

**Comment by call-me-nick** [comment]
I was getting the same error with release v2.8.0, but with ignore_users in my syncmap.  Using hash 2ed3afc (current main:HEAD) works fine, for me.  Can we get a new release, please?  :pray:

**Comment by primetheus** [comment]
@Smirl @call-me-nick this is published in [v2.8.1](https://github.com/3rd-party-integrations/github-team-sync/releases/tag/v2.8.1). Please let me know if that fixes your issue

**Comment by primetheus** [comment]
Closing, as it _should_ be resolved in [v2.8.1](https://github.com/3rd-party-integrations/github-team-sync/releases/tag/v2.8.1)
