### ISSUE TITLE
Github and AAD Sync Mismatch

### ISSUE THREAD

**Issue by JaminenB** [3rd-party-integrations/github-team-sync#202]
I may not be understanding the custom attributes and full capabilities of using Azure AD, and would like some guidance if anyone has more info especially with incorporating this with Github Enterprise Cloud that has different username naming convention. 

In .env.example.aad for connecting to Azure AD, it references the userPrincipalName. In this case, the value is exactly as expected "username@company.com" :
`AZURE_USERNAME_ATTRIBUTE=userPrincipalName`

In Github Enterprise Cloud, however, they append a value to the username and I'm not quite sure on how to use the custom attributes or any mapping to correlate the username (or email address, both are appended with a different delimiter) to the AAD userPrincipalName (email address).

Example of the values in GHEC
```
username = username_company
email = username+company@company.com
```

And the userPrincipalName is just company email address:
```
userPrincipalName = username@company.com
```

**Comment by JaminenB** [comment]
Well, I did a little hack to make it work given the scenario above. Changed USER_SYNC_ATTRIBUTE to **username** and set AZURE_USER_IS_UPN to **true**.  Then made the following change on [app.py](https://github.com/3rd-party-integrations/github-team-sync/blob/main/app.py#L218):

I changed the following from this:
```
team.add_or_update_membership(user)
```

To this:
```
team.add_or_update_membership(f"{user}_company")
```

And that seems to have worked given the problem I have.  From the original attributes provided and my given scenario am I missing where to do this natively without the changes I've made?

**Comment by JaminenB** [comment]
After the initial run, the users were still seen as not belonging due to username mismatch from the Azure directory and thus being removed.  I changed this line as well so that it modified the username field pulled in from AAD to match my previous change as well:
From:
```
group_members = [member for member in members]
```

To:
```
group_members = [{"username": member["username"] + "_company", "email": member["email"]} for member in members]
```

Still believe I'm missing some custom attribute already established, but if not perhaps a PR would make more sense to accommodate the appended "_company" value for companies using GHEC; and append nothing if not value is empty or nonexistent.

**Comment by primetheus** [comment]
@JaminenB thank you for opening this up! Can you tell me which release version you're using?

**Comment by primetheus** [comment]
In looking at this one, it seems to be related to Enterprise Managed Users (EMU)... I think a better approach to fixing it will be to add in some additional logic so it's configurable via `.env` or YAML file.

**Comment by JaminenB** [comment]
I'm thinking I had fried my brain, stared at the screen too much, or been in the wrong branch because I didn't notice the EMU_SHORTCODE variable.  After a long break from looking at this I saw the variable and noticed it is called in azuread.py too, so I reverted all my changes and used the appropriate EMU_SHORTCODE which resolved my issue.
